chart: redis-operator
project: cluster-tools
namespaceLabels:
  pod-security.kubernetes.io/audit: privileged
  pod-security.kubernetes.io/enforce: privileged
  pod-security.kubernetes.io/warn: privileged
path: operator
targetRevision: HEAD
gitValueFiles:
  - values.yaml
